/*============================================================================*/
#include "peripheral_controller.h"
#include "../../pic18f4520/gpio/gpio.h"
#include "../../board/pinout/pinout.h"
/*============================================================================*/
void Peripheral_Controller(void* args)
{
    // LEDHEARTBEAT DIRECTION CONFIGURATION
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, LED_HEARTBEAT1_PORT, LED_HEARTBEAT1_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, LED_HEARTBEAT2_PORT, LED_HEARTBEAT2_MASK);
    
    // DISPLAY PIN DIRECTION
    /*
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_DS_INTERFACE_PORT, DISPLAY_DS_INTERFACE_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_OE_INTERFACE_PORT, DISPLAY_OE_INTERFACE_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_CLK_INTERFACE_PORT, DISPLAY_CLK_INTERFACE_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_LATCH_INTERFACE_PORT,  DISPLAY_LATCH_INTERFACE_MASK);
    */
    
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_LCD_D4_PORT, DISPLAY_LCD_D4_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_LCD_D5_PORT, DISPLAY_LCD_D5_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_LCD_D6_PORT, DISPLAY_LCD_D6_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_LCD_D7_PORT, DISPLAY_LCD_D7_MASK);
    
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_LCD_RS_PORT, DISPLAY_LCD_RS_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DISPLAY_LCD_EN_PORT, DISPLAY_LCD_EN_MASK);
    
    // BLUETOOTH PIN DIRECTION
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, BLUETOOTH_TX_PORT, BLUETOOTH_TX_MASK);
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, BLUETOOTH_RX_PORT, BLUETOOTH_RX_MASK);
    
    
    // DHT11 PIN DIRECTION
    PIN_CONFIGURE_DIGITAL(PIN_OUTPUT, DHT11_DATA_PORT, DHT11_DATA_MASK);

}
/*============================================================================*/